"""ASS V2에서 함께 사용하는 설정값을 모아 둔 파일입니다."""

# 게임 창의 크기입니다.
SCREEN_WIDTH = 1000
SCREEN_HEIGHT = 700

# 게임 화면이 너무 빠르게 반복되지 않도록 초당 프레임 수를 정합니다.
FPS = 60
MAX_DELTA_TIME = 0.05

# 화면에 사용할 색상입니다.
GREEN_BACKGROUND = (34, 139, 34)
GRAY_ROAD = (110, 110, 110)
YELLOW_CENTER_LINE = (255, 215, 0)
WHITE_ROAD_EDGE = (245, 245, 245)
RED_CAR_BODY = (220, 45, 45)
DARK_RED_CAR_DETAIL = (150, 20, 20)
BLUE_CAR_BODY = (45, 95, 230)
DARK_BLUE_CAR_DETAIL = (20, 45, 150)
OPPONENT_CAR_BODY = (35, 190, 170)
OPPONENT_CAR_DETAIL = (15, 105, 95)
SKY_BLUE_WINDOW = (135, 206, 235)
BLACK_TIRE = (15, 15, 15)
WHITE_TEXT = (255, 255, 255)
SENSOR_LINE_COLOR = (255, 245, 120)
DETECTED_SENSOR_LINE_COLOR = (255, 85, 45)

# 왕복 6차선 도로를 만들기 위한 차선 개수입니다.
TOTAL_LANE_COUNT = 6
ONE_WAY_LANE_COUNT = TOTAL_LANE_COUNT // 2

# 차선 폭은 화면 너비를 기준으로 정하고, 도로 폭은 차선 6개를 합쳐 계산합니다.
LANE_WIDTH = int(SCREEN_WIDTH * 0.12)
ROAD_WIDTH = LANE_WIDTH * TOTAL_LANE_COUNT

# 도로가 화면 중앙에 오도록 왼쪽/오른쪽 경계 위치를 계산합니다.
LEFT_ROAD_EDGE_X = (SCREEN_WIDTH - ROAD_WIDTH) // 2
RIGHT_ROAD_EDGE_X = LEFT_ROAD_EDGE_X + ROAD_WIDTH

# 도로/차선 관련 숫자값입니다.
CENTER_LINE_WIDTH = 6
ROAD_EDGE_LINE_WIDTH = 5
LANE_SEPARATOR_LINE_WIDTH = 4
LANE_DASH_LENGTH = 70
LANE_DASH_GAP = 45

# 자동차의 크기와 이동 속도입니다.
CAR_WIDTH = int(LANE_WIDTH * 0.5)
CAR_HEIGHT = int(CAR_WIDTH * 1.8)
CAR_BOTTOM_MARGIN = 45
CAR_CAMERA_LIMIT_Y = int(SCREEN_HEIGHT * 0.7)
CAR_MAX_FORWARD_SPEED = 300
CAR_MAX_REVERSE_SPEED = 170
CAR_ACCELERATION = 420
CAR_DECELERATION = 520
CAR_SIDE_SPEED = 260
CAR_STOP_SPEED = 5
CAR_DIAGONAL_SPEED_FACTOR = 0.7071

# 각 차선의 가운데 X좌표입니다.
LANE_CENTER_X_LIST = tuple(
    LEFT_ROAD_EDGE_X + (lane_index * LANE_WIDTH) + (LANE_WIDTH // 2)
    for lane_index in range(TOTAL_LANE_COUNT)
)
LEFT_DIRECTION_LANE_INDICES = tuple(range(ONE_WAY_LANE_COUNT))
RIGHT_DIRECTION_LANE_INDICES = tuple(range(ONE_WAY_LANE_COUNT, TOTAL_LANE_COUNT))

# 노란색 중앙 분리선은 왼쪽 3개 차선과 오른쪽 3개 차선 사이에 있습니다.
CENTER_DIVIDER_LINE_X = LEFT_ROAD_EDGE_X + (LANE_WIDTH * ONE_WAY_LANE_COUNT)

# 자동차가 처음 시작할 위치입니다.
RIGHT_DIRECTION_MIDDLE_LANE_INDEX = ONE_WAY_LANE_COUNT + (ONE_WAY_LANE_COUNT // 2)
START_CAR_CENTER_X = LANE_CENTER_X_LIST[RIGHT_DIRECTION_MIDDLE_LANE_INDEX]
START_CAR_X = START_CAR_CENTER_X - (CAR_WIDTH // 2)
START_CAR_Y = SCREEN_HEIGHT - CAR_HEIGHT - CAR_BOTTOM_MARGIN

# 장애물 자동차의 처음 위치입니다.
OBSTACLE_CAR_LANE_INDEX = RIGHT_DIRECTION_MIDDLE_LANE_INDEX
OBSTACLE_CAR_DISTANCE_AHEAD = 500
OBSTACLE_CAR_WORLD_Y = START_CAR_Y - OBSTACLE_CAR_DISTANCE_AHEAD

# 상대 차량 생성과 기본 자동 주행 설정입니다.
OPPONENT_CAR_COUNT = 8
OPPONENT_CAR_MAX_COUNT = 18
OPPONENT_CAR_MIN_START_GAP = 320
OPPONENT_CAR_START_DISTANCE_AHEAD = 300
OPPONENT_CAR_MIN_SPAWN_INTERVAL_DISTANCE = 520
OPPONENT_CAR_MAX_SPAWN_INTERVAL_DISTANCE = 950
OPPONENT_CAR_MIN_SPAWN_AHEAD_DISTANCE = 1000
OPPONENT_CAR_MAX_SPAWN_AHEAD_DISTANCE = 1500
OPPONENT_CAR_SPAWN_MAX_ATTEMPTS = 8
OPPONENT_CAR_SAFE_SPAWN_GAP = 300
OPPONENT_CAR_PLAYER_SAFE_SPAWN_GAP = 900
OPPONENT_CAR_DELETE_DISTANCE = 3000
OPPONENT_CAR_SAME_DIRECTION_SPEED = 140
OPPONENT_CAR_OPPOSITE_DIRECTION_SPEED = 165
OPPONENT_CAR_FORWARD_DIRECTION = -1
OPPONENT_CAR_REVERSE_DIRECTION = 1

# 자동차를 구성하는 부품들의 크기입니다.
CAR_BORDER_WIDTH = 4
CAR_WINDOW_WIDTH = 34
CAR_WINDOW_HEIGHT = 24
CAR_TIRE_WIDTH = 12
CAR_TIRE_HEIGHT = 26

# 화면 글자와 안전거리 설정입니다.
DISTANCE_TEXT_SIZE = 28
STOP_DISTANCE = 80

# 차량 주변 센서 감지 범위입니다.
FRONT_SENSOR_LENGTH = 600
REAR_SENSOR_LENGTH = 300
SIDE_SENSOR_LENGTH = LANE_WIDTH + 20
FRONT_REAR_SENSOR_WIDTH = CAR_WIDTH
SIDE_SENSOR_WIDTH = CAR_HEIGHT
SENSOR_LINE_WIDTH = 2
