"""ASS V2에서 함께 사용하는 설정값을 모아 둔 파일입니다."""

# 게임 창의 크기입니다.
SCREEN_WIDTH = 1000
SCREEN_HEIGHT = 700

# 게임 화면이 너무 빠르게 반복되지 않도록 초당 프레임 수를 정합니다.
FPS = 60

# 화면에 사용할 색상입니다.
GREEN_BACKGROUND = (34, 139, 34)
GRAY_ROAD = (110, 110, 110)
YELLOW_CENTER_LINE = (255, 215, 0)
WHITE_ROAD_EDGE = (245, 245, 245)
RED_CAR_BODY = (220, 45, 45)
DARK_RED_CAR_DETAIL = (150, 20, 20)
BLUE_CAR_BODY = (45, 95, 230)
DARK_BLUE_CAR_DETAIL = (20, 45, 150)
SKY_BLUE_WINDOW = (135, 206, 235)
BLACK_TIRE = (15, 15, 15)
WHITE_TEXT = (255, 255, 255)
SENSOR_LINE_COLOR = (255, 245, 120)

# 왕복 6차선 도로를 만들기 위한 차선 개수입니다.
TOTAL_LANE_COUNT = 6
ONE_WAY_LANE_COUNT = TOTAL_LANE_COUNT // 2

# 차선 폭은 화면 너비를 기준으로 정하고, 도로 폭은 차선 6개를 합쳐 계산합니다.
LANE_WIDTH = int(SCREEN_WIDTH * 0.12)
ROAD_WIDTH = LANE_WIDTH * TOTAL_LANE_COUNT

# 도로가 화면 중앙에 오도록 왼쪽/오른쪽 경계 위치를 계산합니다.
LEFT_ROAD_EDGE_X = (SCREEN_WIDTH - ROAD_WIDTH) // 2
RIGHT_ROAD_EDGE_X = LEFT_ROAD_EDGE_X + ROAD_WIDTH

# 도로/차선 관련 숫자값입니다.
CENTER_LINE_WIDTH = 6
ROAD_EDGE_LINE_WIDTH = 5
LANE_SEPARATOR_LINE_WIDTH = 4
LANE_DASH_LENGTH = 70
LANE_DASH_GAP = 45
ROAD_SCROLL_SPEED = 5

# 자동차의 크기와 이동 속도입니다.
CAR_WIDTH = int(LANE_WIDTH * 0.5)
CAR_HEIGHT = int(CAR_WIDTH * 1.8)
CAR_BOTTOM_MARGIN = 45
CAR_SPEED = 5
CAR_CAMERA_LIMIT_Y = int(SCREEN_HEIGHT * 0.7)

# 각 차선의 가운데 X좌표입니다.
LANE_CENTER_X_LIST = tuple(
    LEFT_ROAD_EDGE_X + (lane_index * LANE_WIDTH) + (LANE_WIDTH // 2)
    for lane_index in range(TOTAL_LANE_COUNT)
)

# 노란색 중앙 분리선은 왼쪽 3개 차선과 오른쪽 3개 차선 사이에 있습니다.
CENTER_DIVIDER_LINE_X = LEFT_ROAD_EDGE_X + (LANE_WIDTH * ONE_WAY_LANE_COUNT)

# 자동차가 처음 시작할 위치입니다.
RIGHT_DIRECTION_MIDDLE_LANE_INDEX = ONE_WAY_LANE_COUNT + (ONE_WAY_LANE_COUNT // 2)
START_CAR_CENTER_X = LANE_CENTER_X_LIST[RIGHT_DIRECTION_MIDDLE_LANE_INDEX]
START_CAR_X = START_CAR_CENTER_X - (CAR_WIDTH // 2)
START_CAR_Y = SCREEN_HEIGHT - CAR_HEIGHT - CAR_BOTTOM_MARGIN

# 장애물 자동차의 처음 위치입니다.
OBSTACLE_CAR_LANE_INDEX = RIGHT_DIRECTION_MIDDLE_LANE_INDEX
OBSTACLE_CAR_DISTANCE_AHEAD = 500
OBSTACLE_CAR_WORLD_Y = START_CAR_Y - OBSTACLE_CAR_DISTANCE_AHEAD

# 자동차를 구성하는 부품들의 크기입니다.
CAR_BORDER_WIDTH = 4
CAR_WINDOW_WIDTH = 34
CAR_WINDOW_HEIGHT = 24
CAR_TIRE_WIDTH = 12
CAR_TIRE_HEIGHT = 26

# 화면 글자와 안전거리 설정입니다.
DISTANCE_TEXT_SIZE = 28
STOP_DISTANCE = 80
